substitutions:
  name: "smart-printer-board"
  friendly_name: "MrPresident Smart Printer Board"
  project_name: "MrPresident SmartHome.Smart Printer Board"
  project_version: "1.1"
  Led_number: '100'   #To change the number of leds

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# This should point to the public location of this yaml file.
#dashboard_import:
# package_import_url: github://MrPresident2/MrPresident-Smart-Hot-Plate/smart-hot-plate.yaml@main
 # import_full_config: True

wifi:

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name}"
    password: ""

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:

web_server:
  port: 80

captive_portal:


light:
  - platform: esp32_rmt_led_strip
    id: LED
    rgb_order: GRB
    pin: GPIO15
    num_leds: "${Led_number}"
    rmt_channel: 0
    chipset: SK6812
    is_rgbw: True
    default_transition_length: 0.4s
    name: "LED"

switch:
  - platform: gpio
    pin: 2
    inverted: false
    name: "Printer"
    id: Printer
    internal: False
    icon: mdi:printer-3d-nozzle

binary_sensor:
  - platform: gpio
    pin:
      number: 5
      mode:
        input: true
        pullup: true
      inverted: true    
    name: "LED Button"
    on_press:
      then:
        - logger.log: "LED_Button"
        - light.toggle: LED

  - platform: gpio
    pin:
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true    
    name: "Printer Button"
    on_multi_click:
    - timing:
        - ON for at most 1s
        - OFF for at most 1s
        - ON for at most 1s
        - OFF for at least 0.2s
      then:
      - logger.log: "Printer_Button"
      - switch.toggle: Printer
    